version: '3.7'
services:

  db:
    image: postgres:14.2
    restart: always
    container_name: itea_demo
    networks:
      - itea_demo_network
    ports:
      - "5432:5432"
    env_file:
      - db.env
    volumes:
      - db:/var/lib/postgresql/data

  service:
    image: itea/demo-app:latest
    container_name: itea_demo-app
    networks:
      - itea_demo_network
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_ACTIVE_PROFILE=prod
volumes:
  db:
    driver: local

networks:
  itea_demo_network:
    name: itea_demo_network
