version: '3.7'
services:

  db:
    image: postgres:14.2
    restart: always
    container_name: itea_demo
    ports:
      - "5432:5432"
    env_file:
      - db.env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app-network

  messenger:
    image: messenger
    container_name: app_messenger
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - SPRING_ACTIVE_PROFILE=prod

volumes:
  db:
    driver: local

networks:
  app-network:
    name: app-network